name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the project
      run: ./gradlew assemble
    - name: detekt
      uses: natiginfo/action-detekt-all@1.15.0-RC1
